[package]
name = "easy_teaching_app"
version = "0.1.0"
description = "Easy Teaching desktop app shell powered by Tauri"
authors = ["ZhcChen <chen1406736605@gamil.com>"]
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "easy_teaching_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
